### ISSUE TITLE
Contact Form Issue

### ISSUE THREAD

**Issue by nishabe** [chuckgroom/chuckgroom.github.io#1]
Hello @chuckgroom ,
This is not exactly an issue.
I was going through your repo as well as 'BlackrockDigital/startbootstrap-freelancer' repo in order to use it in github pages.

Could you please elaborate on the code changes to be made on freelancer repo in order to make the 'Contact Me' form working?
I have added the 'formspree' url in the action tag. However, it looks like the php code is getting called which results in 'https://nishabe.github.io/mail/contact_me.php 405 ()' error.
Could you please advise?

**Comment by chuckgroom** [comment]
Hi @nishabe, I actually didn't use the PHP version, but instead the static javascript used here: https://github.com/chuckgroom/chuckgroom.github.io/blob/master/_includes/contact_static.html

"{{ site.email }}" is populated using the config.yml file value. 
 
Hope that helps!

**Comment by nishabe** [comment]
Thanks for your reply.
That was simple. 💯.
However, in this case, there was one more step needed which is renaming the form id to anything other than 'contactForm'. The jQuery was bound with the name 'contactForm' which was again calling the php script.

Thanks a ton!
